# Generated by Django 5.2.4 on 2025-07-19 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_access_alter_course_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_preview', models.BooleanField(default=False, help_text='if the user doesnt have access to the course, can he see this?')),
                ('status', models.CharField(choices=[('published', 'Published'), ('soon', 'Coming Soon'), ('draft', 'Draft')], default='published', max_length=11)),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
